version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: legorachat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: legorachat
      DB_PASSWORD: password
      DB_PORT: 5432
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
